//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLogic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillDetail()
        {
            this.BillEmployees = new HashSet<BillEmployee>();
        }
    
        public long ID { get; set; }
        public Nullable<long> QuotationID { get; set; }
        public Nullable<long> BillID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillEmployee> BillEmployees { get; set; }
        public virtual MaintenanceBill MaintenanceBill { get; set; }
        public virtual QuotationTable QuotationTable { get; set; }
    }
}
