//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLogic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRole
    {
        public long ID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<long> RoleID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
