//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLogic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceBill()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<long> BikeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> CashierID { get; set; }
        public string CustomerPayment { get; set; }
        public Nullable<long> StoreID { get; set; }
    
        public virtual Bike Bike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Store Store { get; set; }
    }
}
