//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessLogic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReceipt
    {
        public long ID { get; set; }
        public Nullable<long> CashierID { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<long> BikeID { get; set; }
        public Nullable<long> StoreID { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Store Store { get; set; }
    }
}
